#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

echo "Start building ISO image"

HARVESTER_INSTALLER_VERSION=v1.0.3

git clone --single-branch --depth 1 https://github.com/inaccel/harvester-installer.git ../harvester-installer

cd ../harvester-installer/scripts

./ci

cd ..
HARVESTER_DIR=../harvester

mkdir -p ${HARVESTER_DIR}/dist/artifacts
cp dist/artifacts/* ${HARVESTER_DIR}/dist/artifacts

